name: "Validate features"
on:
  workflow_dispatch:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Validate feature definitions"
        uses: devcontainers/action@v1
        with:
          features-namespace: roul/devcontainer-features
          validate-only: "true"
          base-path-to-features: "./src"
